apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  type: LoadBalancer  # Use ClusterIP if external access isn't needed
  selector:
    app: django-app
  ports:
    - port: 8000
      targetPort: 8000
