apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: sayanchak97/test_97:latest  # Replace with your Docker Hub image
        ports:
        - containerPort: 8000
        env:
          - name: MYSQL_HOST
            value: mysql
          - name: MYSQL_DB
            value: "django-app-db"
        resources:
          requests:
            memory: "256Mi"  # Minimum amount of memory the container needs
            cpu: "250m"      # Minimum amount of CPU the container needs
          limits:
            memory: "512Mi"  # Maximum amount of memory the container is allowed to use
            cpu: "500m"      # Maximum amount of CPU the container is allowed to use
